'use client';
import {useState} from 'react';
import {Printer,Plus} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {saveFile} from '@/lib/client';

export default function PrintPanel({data,busy,onBatch}:{data:any;busy:boolean;onBatch:()=>void}){const[batch,setBatch]=useState('latest');const[width,setWidth]=useState(66.675);const[height,setHeight]=useState(25.4);const[marginX,setMarginX]=useState(4.7625);const[marginY,setMarginY]=useState(12.7);const[gapX,setGapX]=useState(3.175);const[gapY,setGapY]=useState(0);const[paper,setPaper]=useState('letter');const[test,setTest]=useState(true);const[exporting,setExporting]=useState(false);const[unusedOnly,setUnusedOnly]=useState(true);
 const batches=[...new Set<string>((data?.qrs||[]).filter((q:any)=>q.batch_id!=='demo').map((q:any)=>q.batch_id))];const codes=(data?.qrs||[]).filter((q:any)=>q.batch_id!=='demo'&&(batch==='all'||q.batch_id===(batch==='latest'?batches[batches.length-1]:batch))&&(!unusedOnly||!q.assigned_at));const ready=!!data?.settings.origin&&/^https:\/\//.test(data.settings.origin)&&!data.settings.local;
 async function print(){setExporting(true);try{const origin=test?location.origin:data.settings.origin;if(!test&&!ready)throw Error('Configure the permanent HTTPS domain before printing live stickers.');const {stickerPDF}=await import("@/lib/sticker-pdf");const result=await stickerPDF(codes,{origin,width,height,marginX,marginY,gapX,gapY,paper:paper as 'letter'|'a4',test});saveFile(new Blob([result as BlobPart],{type:'application/pdf'}),`spray-net-${test?'TEST-':''}qr-stickers.pdf`);toast.success('PDF downloaded. Print at Actual size / 100%.');}catch(e){toast.error((e as Error).message);}finally{setExporting(false);}}
 return <section className="panel stack"><div className="section-heading"><div><h2>Print now. Assign later.</h2><p>Each batch contains 100 unique QR links.</p></div><button disabled={busy} onClick={onBatch}><Plus/>Generate 100 codes</button></div><div className="field-grid"><label>Codes to print<Select value={batch} onValueChange={setBatch}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="latest">Latest batch</SelectItem><SelectItem value="all">All batches</SelectItem>{batches.map((b,i)=><SelectItem key={b} value={b}>Batch {i+1} · {b.slice(0,8)}</SelectItem>)}</SelectContent></Select></label><label>Paper<Select value={paper} onValueChange={setPaper}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="letter">US Letter · 8.5 × 11 in</SelectItem><SelectItem value="a4">A4</SelectItem></SelectContent></Select></label></div><div className="field-grid">{[['Label width',width,setWidth],['Label height',height,setHeight],['Left/right margin',marginX,setMarginX],['Top/bottom margin',marginY,setMarginY],['Horizontal gap',gapX,setGapX],['Vertical gap',gapY,setGapY]].map(([label,value,setter]:any)=><label key={label}>{label} (mm)<input type="number" step="0.01" min="0" value={value} onChange={e=>setter(Number(e.target.value))}/></label>)}</div><small>Defaults fit common 30-label US Letter sheets (2⅝ × 1 inch). Measure your stock before live printing.</small><label className="selection-label"><Checkbox checked={unusedOnly} onCheckedChange={v=>setUnusedOnly(v===true)}/>Print unused codes only</label><label className="selection-label"><Checkbox checked={test} onCheckedChange={v=>setTest(v===true)} disabled={!ready}/>Test sheet · labeled TEST and linked to this preview</label>{!ready&&<div className="notice">Live printing is locked until the permanent domain is configured. Test codes are for this preview only.</div>}<button disabled={exporting||!codes.length} onClick={print}><Printer/>{exporting?'Preparing PDF…':`Download ${test?'test ':''}sticker PDF (${codes.length} codes)`}</button><small>Print at 100% / Actual size. Scan a printed sample before distributing cards.</small></section>;
}
