import {test,expect} from './test';
import {authenticate} from '../backend/auth';
import worker from '../backend/worker';
import type {Env} from '../backend/types';
const env:Env={ENVIRONMENT:'production',ADMIN_EMAILS:'ben.hessler@spray-net.com',SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-test-key',LOCAL_ADMIN_TOKEN:'local-test-token',ALLOWED_ORIGINS:'https://benjamin41997-ctrl.github.io'};
function request(token='signed-access-token'){return new Request('https://api.example.com/api/admin/session',{headers:{Authorization:'Bearer '+token}});}
function verified(email:string,confirmed=true,anonymous=false){return (async(input:any,init:any)=>{expect(new URL(input).href).toBe('https://example.supabase.co/auth/v1/user');expect(init.headers.Authorization).toBe('Bearer signed-access-token');expect(init.headers.apikey).toBe('public-test-key');return Response.json({id:'verified-user',email,email_confirmed_at:confirmed?'2026-10-02T00:00:00Z':null,is_anonymous:anonymous});}) as typeof fetch;}
test('server requires a confirmed, non-anonymous, allowlisted Supabase identity',async()=>{expect(await authenticate(request(),env,verified('BEN.HESSLER@SPRAY-NET.COM'))).toBe(true);expect(await authenticate(request(),env,verified('other@example.com'))).toBe(false);expect(await authenticate(request(),env,verified('ben.hessler@spray-net.com',false))).toBe(false);expect(await authenticate(request(),env,verified('ben.hessler@spray-net.com',true,true))).toBe(false);});
test('a forged JWT, auth failure, or unreachable provider fails closed',async()=>{expect(await authenticate(request('forged'),env,(async()=>new Response(null,{status:401})) as typeof fetch)).toBe(false);expect(await authenticate(request(),env,(async()=>{throw Error('Offline');}) as typeof fetch)).toBe(false);expect(await authenticate(new Request('https://api.example.com/api/admin/session',{headers:{'oai-authenticated-user-email':'ben.hessler@spray-net.com'}}),env)).toBe(false);});
test('production never accepts local preview tokens or exposes local sign-in',async()=>{expect(await authenticate(request('local-test-token'),{...env,SUPABASE_URL:''})).toBe(false);expect(await authenticate(new Request('http://127.0.0.1:8787/api/admin/session',{headers:{Authorization:'Bearer local-test-token'}}),{...env,SUPABASE_URL:''})).toBe(false);const r=await worker.fetch(new Request('https://api.example.com/api/local/signin',{method:'POST',headers:{Origin:'https://benjamin41997-ctrl.github.io'}}),env);expect(r.status).toBe(404);expect(await r.text()).not.toContain('local-test-token');});
