import {test,expect,request,APIRequestContext} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir} from 'node:fs/promises';
const base='http://127.0.0.1:5173';let admin:APIRequestContext;let tokens:string[];let sample:any;
const jdata={internal_name:'QA private customer name',title:'Your finished kitchen',source:'angi',links:{google:'https://g.page/r/test/review',angi:'https://www.angi.com/write-review/test',thumbtack:'https://www.thumbtack.com/reviews/test',yelp:'https://www.yelp.com/biz/test'}};
async function post(path:string,data:any){return admin.post('/api/'+path,{data,headers:{Origin:base}});}
async function make(){return (await post('admin/jobs',jdata)).json();}
async function patch(j:any,status:string){return admin.patch('/api/admin/jobs/'+j.id,{data:{...j,status},headers:{Origin:base}});}
test.beforeAll(async()=>{admin=await request.newContext({baseURL:base});await admin.get('/signin-with-chatgpt?return_to=/admin');await post('admin/batch',{count:100});const d=await(await admin.get('/api/admin/dashboard')).json();tokens=d.qrs.filter((q:any)=>!q.assigned_at).map((q:any)=>q.token);sample=await(await post('admin/seed',{})).json();});
test.afterAll(async()=>{await admin.dispose();});
test('a scanned unused sticker stays selected when creating its project',async({page,request})=>{
 const token=tokens.pop()!;
 await page.goto('/signin-with-chatgpt?return_to='+encodeURIComponent('/admin?code='+token));
 await page.getByRole('button',{name:'Create a new project first'}).click();
 await page.getByLabel('Internal customer / job name',{exact:true}).fill('Scanned sticker QA');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 const d=await(await admin.get('/api/admin/dashboard')).json();const j=d.jobs.find((j:any)=>j.internal_name==='Scanned sticker QA');
 expect(d.qrs.find((q:any)=>q.token===token).assigned_at).toBeNull();
 expect((await request.get('/admin/preview/'+j.id)).status()).toBe(404);
 expect((await admin.get('/admin/preview/'+j.id)).status()).toBe(200);
 await page.getByRole('button',{name:/Assign SN-.* to project/}).click();
 await expect(page.getByText('Sticker assigned permanently to this project.')).toBeVisible();
 const assigned=await(await admin.get('/api/admin/jobs/'+j.id)).json();expect(assigned.qrs[0].token).toBe(token);
 await admin.delete('/api/admin/jobs/'+j.id,{headers:{Origin:base}});
});
test('anonymous writes, forged identity and cross-origin writes are rejected',async({request})=>{for(const p of ['admin/dashboard','admin/jobs/sample-kitchen','admin/photos/sample-before'])expect((await request.get('/api/'+p)).status()).toBe(403);expect((await request.get('/api/admin/dashboard',{headers:{'oai-authenticated-user-id':'x','oai-authenticated-user-email':'ben.hessler@spray-net.com'}})).status()).toBe(403);expect((await request.post('/api/admin/batch',{data:{count:100},headers:{Origin:base}})).status()).toBe(403);expect((await admin.post('/api/admin/batch',{data:{count:100},headers:{Origin:'https://evil.example'}})).status()).toBe(403);});
test('assignment is atomic; draft, active, archived and deleted pages enforce access',async({request})=>{const a=await make(),b=await make();const token=tokens.shift()!;expect((await request.get('/api/customer/'+token)).status()).toBe(404);const results=await Promise.all([post('admin/assign',{token,job_id:a.id}),post('admin/assign',{token,job_id:b.id})]);expect(results.map(r=>r.status()).sort()).toEqual([200,409]);const assigned=await(await admin.get('/api/admin/dashboard')).json();const id=assigned.qrs.find((q:any)=>q.token===token).job_id;let j=await(await admin.get('/api/admin/jobs/'+id)).json();expect((await request.get('/api/customer/'+token)).status()).toBe(404);j=await(await patch(j,'active')).json();const pub=await(await request.get('/api/customer/'+token)).json();expect(pub.internal_name).toBeUndefined();expect(pub.qrs).toBeUndefined();expect(pub.title).toBe(j.title);expect((await patch({...j,revision:1},'active')).status()).toBe(409);j=await(await patch(j,'archived')).json();expect((await request.get('/api/customer/'+token)).status()).toBe(404);await admin.delete('/api/admin/jobs/'+id,{headers:{Origin:base}});expect((await post('admin/assign',{token,job_id:id===a.id?b.id:a.id})).status()).toBe(409);await admin.delete('/api/admin/jobs/'+(id===a.id?b.id:a.id),{headers:{Origin:base}});});
test('photo access requires the matching live token; deactivation revokes it',async({request})=>{const j=await make();const token=tokens.shift()!;await post('admin/assign',{token,job_id:j.id});const upload=await admin.post('/api/admin/photos',{multipart:{job_id:j.id,kind:'before',label:'Before cabinets',file:{name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY9sAAAAASUVORK5CYII=','base64')}},headers:{Origin:base}});expect(upload.ok()).toBeTruthy();let fresh=await upload.json();fresh=await(await patch(fresh,'active')).json();const photo=fresh.photos[0];expect((await request.get(`/api/customer/${token}/photo/${photo.id}?download=1`)).headers()['content-disposition']).toContain('attachment');expect((await request.get(`/api/customer/${sample.qrs[0].token}/photo/${photo.id}`)).status()).toBe(404);fresh=await(await patch(fresh,'archived')).json();expect((await request.get(`/api/customer/${token}/photo/${photo.id}`)).status()).toBe(404);await admin.delete('/api/admin/jobs/'+j.id,{headers:{Origin:base}});});
test('malformed links, batches and photos are rejected',async()=>{expect((await post('admin/jobs',{...jdata,links:{google:'https://google.com.evil.example'}})).status()).toBe(400);expect((await post('admin/batch',{count:101})).status()).toBe(400);expect((await admin.post('/api/admin/photos',{multipart:{job_id:sample.id,kind:'after',label:'Fake JPEG',file:{name:'fake.jpg',mimeType:'image/jpeg',buffer:Buffer.from('<script>bad</script>')}},headers:{Origin:base}})).status()).toBe(400);});
test('customer draft persists; native platform first; no publication claim',async({page})=>{const j=await make();const token=tokens.shift()!;await post('admin/assign',{token,job_id:j.id});await patch(j,'active');await page.goto('/q/'+token);await expect(page.getByRole('heading',{name:'Your finished kitchen'})).toBeVisible();const text='Cabinets look good. The start was a day late.';await page.getByLabel('Your review',{exact:true}).fill(text);await page.getByRole('checkbox',{name:'I’ve checked this text.'}).check();await page.reload();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue(text);await expect(page.getByRole('checkbox',{name:'I’ve checked this text.'})).toBeChecked();expect(await page.locator('.destination a.button').first().textContent()).toContain('Angi');await expect(page.getByRole('link',{name:'Business information on Yelp'})).toBeVisible();await expect(page.getByRole('link',{name:'Continue to Yelp'})).toHaveCount(0);await page.getByRole('checkbox',{name:'I submitted on Angi'}).check();const d=await(await admin.get('/api/admin/dashboard')).json();const row=d.jobs.find((x:any)=>x.id===j.id);expect(row.visits).toBe(1);expect(row.clicks).toBe(0);expect(row.reported).toBe(1);await page.getByRole('button',{name:'Talk about your experience'}).click();await expect(page.getByText('Voice transcription isn’t connected yet.',{exact:false})).toBeVisible();await expect(page.getByText('AI spelling',{exact:false})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const axe=await new AxeBuilder({page}).analyze();expect(axe.violations).toEqual([]);await mkdir('.sites-runtime/qa',{recursive:true});await page.screenshot({path:`.sites-runtime/qa/customer-${test.info().project.name}.png`,fullPage:true});await admin.delete('/api/admin/jobs/'+j.id,{headers:{Origin:base}});});
test('admin project creation, mobile photo upload, activation and PDF export',async({page})=>{await page.goto('/signin-with-chatgpt?return_to=/admin');await expect(page.getByRole('heading',{name:'Ready for their review.'})).toBeVisible();await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Internal customer / job name',{exact:true}).fill('Browser QA project');await page.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('heading',{name:'Prepare their project.'})).toBeVisible();await page.getByLabel('Google',{exact:true}).fill('https://g.page/r/test/review');await page.locator('input[type=file]').setInputFiles('public/sample/after.webp');await expect(page.getByText('Photo uploaded.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Activate page',exact:true}).click();await expect(page.getByText('Customer page activated.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Assign unused sticker'}).click();await page.getByRole('combobox',{name:'Sticker to assign'}).click();await page.getByRole('option').first().click();await page.getByRole('button',{name:/Assign SN-.* to project/}).click();await expect(page.getByRole('link',{name:'Preview customer page'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`.sites-runtime/qa/admin-editor-${test.info().project.name}.png`,fullPage:true});const axe=await new AxeBuilder({page}).analyze();expect(axe.violations).toEqual([]);await page.getByRole('button',{name:'All projects'}).click();await page.getByRole('tab',{name:'QR stickers'}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:/Download test sticker PDF/}).click();await(await download).saveAs(`.sites-runtime/qa/stickers-${test.info().project.name}.pdf`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`.sites-runtime/qa/qr-${test.info().project.name}.png`,fullPage:false});const d=await(await admin.get('/api/admin/dashboard')).json();const j=d.jobs.find((x:any)=>x.internal_name==='Browser QA project');await admin.delete('/api/admin/jobs/'+j.id,{headers:{Origin:base}});});
