import {test,expect} from '@playwright/test';
import {login,browserAdmin,site,origin} from './helpers';
test('recording, transcription and rejection of AI edits preserve customer control',async({page})=>{
 const {admin,token}=await login();const sample=await(await admin.post('/api/admin/seed',{data:{}})).json();await admin.dispose();await browserAdmin(page,token);
 await page.addInitScript(()=>{const AudioCtx=window.AudioContext||(window as any).webkitAudioContext;let context:any;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{context=new AudioCtx();const oscillator=context.createOscillator();const output=context.createMediaStreamDestination();oscillator.connect(output);oscillator.start();return output.stream;}});});
 await page.route('**/api/customer/'+sample.qrs[0].token+'?preview=1',async route=>{const response=await route.fetch();const data=await response.json();data.settings={transcription:true,cleanup:true};await route.fulfill({response,json:data});});
 const headers={'Access-Control-Allow-Origin':origin};
 await page.route('**/api/customer/*/transcribe',r=>r.fulfill({headers,json:{text:'The cabinets look good. We started a day late.'}}));await page.route('**/api/customer/*/cleanup',r=>r.fulfill({headers,json:{text:'The cabinets look good. The job started a day late.'}}));
 await page.goto(site+'?code='+sample.qrs[0].token+'&preview=1');await page.getByRole('button',{name:'Talk about your experience'}).click();
 if(!await page.evaluate(()=>typeof MediaRecorder!=='undefined')){await expect(page.getByText('Recording is unavailable in this browser.',{exact:false})).toBeVisible();await page.getByLabel('Your review',{exact:true}).fill('Typing still works.');return;}
 await expect(page.getByRole('button',{name:/Stop recording/})).toBeVisible();await page.getByRole('button',{name:/Stop recording/}).click();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('The cabinets look good. We started a day late.');await page.getByRole('button',{name:'Optional AI spelling and grammar cleanup'}).click();await expect(page.getByRole('heading',{name:'Check the suggested edit'})).toBeVisible();await page.getByRole('button',{name:'Keep my original'}).click();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('The cabinets look good. We started a day late.');await expect(page.getByRole('checkbox',{name:'I’ve checked this text.'})).not.toBeChecked();
});
test('microphone permission denial or lack of recording support preserves the draft',async({page})=>{
 const {admin,token}=await login();const sample=await(await admin.post('/api/admin/seed',{data:{}})).json();await admin.dispose();await browserAdmin(page,token);
 await page.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{throw new DOMException('Denied','NotAllowedError');}}));
 await page.route('**/api/customer/'+sample.qrs[0].token+'?preview=1',async route=>{const response=await route.fetch();const data=await response.json();data.settings={transcription:true,cleanup:false};await route.fulfill({response,json:data});});
 await page.goto(site+'?code='+sample.qrs[0].token+'&preview=1');await page.getByLabel('Your review',{exact:true}).fill('My original feedback.');const supported=await page.evaluate(()=>typeof MediaRecorder!=='undefined');await page.getByRole('button',{name:'Talk about your experience'}).click();await expect(page.getByText(supported?'Microphone access was declined.':'Recording is unavailable in this browser.',{exact:false})).toBeVisible();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('My original feedback.');
});
