import {test,expect,request} from '@playwright/test';
test('recording, transcription, optional edit and rejected suggestion preserve customer control',async({page})=>{
 const req=await request.newContext({baseURL:'http://127.0.0.1:5173'});await req.get('/signin-with-chatgpt?return_to=/admin');const j=await(await req.post('/api/admin/seed',{headers:{Origin:'http://127.0.0.1:5173'},data:{}})).json();await req.dispose();
 await page.addInitScript(()=>{const AudioCtx=window.AudioContext||(window as any).webkitAudioContext;let ctx:any;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{ctx=new AudioCtx();const oscillator=ctx.createOscillator();const destination=ctx.createMediaStreamDestination();oscillator.connect(destination);oscillator.start();return destination.stream;}});});
 await page.route('**/api/customer/*/transcribe',r=>r.fulfill({json:{text:'The cabinets look good. We started a day late.'}}));await page.route('**/api/customer/*/cleanup',r=>r.fulfill({json:{text:'The cabinets look good. The job started a day late.'}}));
 await page.goto('/signin-with-chatgpt?return_to='+encodeURIComponent('/admin/voice-check?token='+j.qrs[0].token));
 const canRecord=await page.evaluate(()=>typeof MediaRecorder!=='undefined');
 await page.getByRole('button',{name:'Talk about your experience'}).click();
 if(!canRecord){await expect(page.getByText('Recording is unavailable in this browser.',{exact:false})).toBeVisible();await page.getByLabel('Your review',{exact:true}).fill('Typing works without recording.');await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('Typing works without recording.');return;}
 await expect(page.getByRole('button',{name:/Stop recording/})).toBeVisible();await page.getByRole('button',{name:/Stop recording/}).click();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('The cabinets look good. We started a day late.');await page.getByRole('button',{name:'Optional AI spelling and grammar cleanup'}).click();await expect(page.getByRole('heading',{name:'Check the suggested edit'})).toBeVisible();await page.getByRole('button',{name:'Keep my original'}).click();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('The cabinets look good. We started a day late.');await expect(page.getByRole('checkbox',{name:'I’ve checked this text.'})).not.toBeChecked();
});
test('microphone denial retains typing fallback and existing draft',async({page})=>{const req=await request.newContext({baseURL:'http://127.0.0.1:5173'});await req.get('/signin-with-chatgpt?return_to=/admin');const j=await(await req.get('/api/admin/jobs/sample-kitchen')).json();await req.dispose();await page.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>{throw new DOMException('Denied','NotAllowedError');}}));await page.goto('/signin-with-chatgpt?return_to='+encodeURIComponent('/admin/voice-check?token='+j.qrs[0].token));await page.getByLabel('Your review',{exact:true}).fill('My original feedback.');const canRecord=await page.evaluate(()=>typeof MediaRecorder!=='undefined');await page.getByRole('button',{name:'Talk about your experience'}).click();await expect(page.getByText(canRecord?'Microphone access was declined.':'Recording is unavailable in this browser.',{exact:false})).toBeVisible();await expect(page.getByLabel('Your review',{exact:true})).toHaveValue('My original feedback.');});
