'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Copy,Download,Check,RotateCcw,Keyboard,Loader2} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {api,orderedPlatforms,platformNames,saveFile} from '@/lib/client';
import {adminLink,assetURL,photoURL as remotePhotoURL} from '@/lib/urls';
import SecurePhoto from './SecurePhoto';
import {getAccessToken} from '@/lib/auth';
type CustomerJob={id:string;title:string;source:string;demo:boolean;links:Record<string,string>;photos:{id:string;kind:string;label:string}[]};
export default function Customer({token,initial,capabilities,preview,admin,jobPreview=false}:{token:string;initial:CustomerJob;capabilities:{transcription:boolean;cleanup:boolean};preview:boolean;admin:boolean;jobPreview?:boolean}){
 const[job]=useState(initial);const[text,setText]=useState('');const[original,setOriginal]=useState('');const[selected,setSelected]=useState<string[]>([]);const[approved,setApproved]=useState(false);const[restored,setRestored]=useState(false);const[storageIssue,setStorageIssue]=useState(false);const[recording,setRecording]=useState(false);const[processing,setProcessing]=useState(false);const[seconds,setSeconds]=useState(0);const[audio,setAudio]=useState<Blob|null>(null);const[audioURL,setAudioURL]=useState('');const[reported,setReported]=useState<string[]>([]);const[edited,setEdited]=useState('');
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const recordingTimer=useRef<ReturnType<typeof setInterval>|null>(null);const limitTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const textarea=useRef<HTMLTextAreaElement>(null);const key=`spraynet-review:v1:${token}`;const base=`customer/${token}`;const photoURL=(id:string,download=false)=>remotePhotoURL(jobPreview?`admin/photos/${id}`:`${base}/photo/${id}`,{preview,download});
 function update(v:string){setText(v);setApproved(false);setEdited('');}
 async function track(type:string,platform?:string){if(preview)return;try{let id:string=crypto.randomUUID();if(type==='reported'){try{const k=key+':confirmation:'+platform;id=localStorage.getItem(k)||id;localStorage.setItem(k,id);}catch{}}await api(`${base}/event`,{method:'POST',body:JSON.stringify({id,type,platform})});}catch{ /* Navigation must stay available if activity storage fails. */ }}
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');if(v&&Date.now()-v.savedAt<30*86400000){setText(v.text||'');setOriginal(v.original||'');setSelected((v.selected||[]).filter((id:string)=>job.photos.some(p=>p.id===id)));setApproved(v.approved===true);setReported(v.reported||[]);}else localStorage.removeItem(key);}catch{setStorageIssue(true);}setRestored(true);
  try{if(!preview&&!sessionStorage.getItem(key+':visit')){track('visit');sessionStorage.setItem(key+':visit','1');}}catch{track('visit');}
  const context=(document as any).modelContext;const lifecycle=new AbortController();if(context?.registerTool){Promise.resolve(context.registerTool({name:'stage_review_text',description:'Place customer-provided text in the editable draft. Does not approve, publish or improve it.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:8000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:any){if(typeof input.text!=='string'||input.text.length>8000)throw Error('Text must be at most 8000 characters.');update(input.text);return {staged:true,approved:false,published:false};}},{signal:lifecycle.signal})).catch(()=>{});}
  return()=>{lifecycle.abort();if(recordingTimer.current)clearInterval(recordingTimer.current);if(limitTimer.current)clearTimeout(limitTimer.current);stream.current?.getTracks().forEach(t=>t.stop());};
 },[key]);
 useEffect(()=>{if(!restored)return;try{localStorage.setItem(key,JSON.stringify({text,original,selected,approved,reported,savedAt:Date.now()}));}catch{setStorageIssue(true);}},[text,original,selected,approved,reported,restored,key]);
 useEffect(()=>{if(!audio){setAudioURL('');return;}const u=URL.createObjectURL(audio);setAudioURL(u);return()=>URL.revokeObjectURL(u);},[audio]);
 function stop(){if(recordingTimer.current)clearInterval(recordingTimer.current);if(limitTimer.current)clearTimeout(limitTimer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);}
 async function transcribe(blob:Blob){setProcessing(true);try{const form=new FormData();const ext=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';form.set('audio',new File([blob],`review.${ext}`,{type:blob.type}));const b=await api(`${base}/transcribe`,{method:'POST',body:form});setOriginal(b.text);update(text?`${text}\n\n${b.text}`:b.text);toast.success('Transcript ready. Please check it before sharing.');}catch(e){toast.error((e as Error).message);}finally{setProcessing(false);}}
 async function start(){if(!capabilities.transcription){toast('Voice transcription isn’t connected yet. Use the microphone on your phone keyboard, or type below.');textarea.current?.focus();return;}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){toast.error('Recording is unavailable in this browser. Please type or use your keyboard’s microphone.');textarea.current?.focus();return;}
  try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const type=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(media,type?{mimeType:type}:undefined);recorder.current=rec;const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=()=>{stop();toast.error('Recording stopped. Please try again or type your review.');};rec.onstop=()=>{const b=new Blob(chunks,{type:rec.mimeType.split(';')[0]});setAudio(b);if(b.size)transcribe(b);};setAudio(null);setSeconds(0);setRecording(true);rec.start();recordingTimer.current=setInterval(()=>setSeconds(s=>s+1),1000);limitTimer.current=setTimeout(stop,120000);
  }catch(e){toast.error((e as Error).name==='NotAllowedError'?'Microphone access was declined. You can allow it in browser settings, or type below.':'The microphone could not start. Please type or try again.');stream.current?.getTracks().forEach(t=>t.stop());}}
 async function copy(){try{await navigator.clipboard.writeText(text);toast.success('Review copied. Paste it on the next page.');}catch{textarea.current?.focus();textarea.current?.select();toast('Select the text above and copy it using your phone’s menu.');}}
 async function savePhotos(){if(!selected.length)return;try{const files=await Promise.all(selected.map(async(id)=>{const accessToken=await getAccessToken();const r=await fetch(photoURL(id,true),{headers:accessToken?{Authorization:'Bearer '+accessToken}:{}});if(!r.ok)throw Error('A photo is unavailable.');const blob=await r.blob();return new File([blob],`spray-net-${job.photos.find(p=>p.id===id)?.kind}-${id.slice(0,8)}.${blob.type==='image/jpeg'?'jpg':blob.type==='image/png'?'png':'webp'}`,{type:blob.type});}));if(navigator.canShare?.({files})&&navigator.share){await navigator.share({files,title:'Your Spray-Net project photos'});}else{for(const f of files)saveFile(f,f.name);toast('Photos downloaded. Attach them yourself on the review page.');}}catch(e){if((e as Error).name!=='AbortError')toast.error((e as Error).message);}}
 async function cleanup(){setProcessing(true);try{const b=await api(`${base}/cleanup`,{method:'POST',body:JSON.stringify({text})});setEdited(b.text);}catch(e){toast.error((e as Error).message);}finally{setProcessing(false);}}
 const destinations=orderedPlatforms(job.source,job.links);
 return <main className="customer-shell">{admin&&<div className="actions"><a className="text-link" href={adminLink({assign:token})}>Manage this sticker</a></div>}{preview&&<div className="notice">Administrator preview · activity is not counted.</div>}{job.demo&&<div className="notice">Sample project · these are Spray-Net network photos, not a South Charlotte customer job.</div>}<header className="brand"><img src={assetURL("branding/logo.png")} alt="Spray-Net"/><p className="eyebrow">SOUTH CHARLOTTE</p></header><div className="intro"><h1>{job.title}</h1><p>Your photos, and a simple way to share your experience.</p><a className="text-link" href="#destinations">Go directly to review options</a></div>
 <div className="photo-grid">{job.photos.map(p=><figure className="photo-card" key={p.id}><SecurePhoto src={photoURL(p.id)} alt={p.label}/><span className="photo-type">{p.kind==='after'?'Now':p.kind}</span><figcaption className="photo-caption">{p.label}</figcaption></figure>)}</div><small style={{marginTop:'.6rem'}}>Project photos supplied by Spray-Net.</small>
 <section className="panel stack"><div><h2><span className="step-number">1</span>Share your experience</h2><p>Speak or type what you’d like other homeowners to know. All honest feedback is welcome.</p></div><button className={recording?'full recording':'full'} disabled={processing||!restored} onClick={recording?stop:start}>{processing?<Loader2/>:recording?<Square/>:<Mic/>}{processing?'Please wait…':recording?`Stop recording · ${seconds}s`:'Talk about your experience'}</button>{!capabilities.transcription&&<small>For now, use your keyboard’s microphone to dictate into the box below.</small>}
 <label>Your review<textarea aria-label="Your review" ref={textarea} disabled={!restored||recording||processing} maxLength={8000} value={text} onChange={e=>update(e.target.value)} placeholder="Write in your own words…"/></label><div className="draft-notice" aria-live="polite"><small>{storageIssue?'Your browser could not save this draft. Copy it before leaving.':restored?'Draft saved on this device for up to 30 days.':''}</small></div>
 {audioURL&&<div className="stack"><audio controls src={audioURL} aria-label="Your recording"/><div className="actions"><button className="secondary" disabled={processing} onClick={()=>audio&&transcribe(audio)}>Retry transcription</button><button className="quiet" onClick={()=>audio&&saveFile(audio,'my-review-recording.'+(audio.type.includes('mp4')?'m4a':'webm'))}>Save recording</button></div></div>}
 {capabilities.cleanup&&<button className="secondary" disabled={!text.trim()||processing} onClick={cleanup}>Optional AI spelling and grammar cleanup</button>}{edited&&<div className="notice stack"><h3>Check the suggested edit</h3><p>Your original</p><blockquote>{text}</blockquote><p>AI suggestion</p><blockquote>{edited}</blockquote><div className="actions"><button onClick={()=>{setText(edited);setEdited('');setApproved(false);}}>Use this version</button><button className="secondary" onClick={()=>setEdited('')}>Keep my original</button></div></div>}
 {original&&original!==text&&<button className="quiet" onClick={()=>update(original)}><RotateCcw/>Restore original transcript</button>}<label className="selection-label"><Checkbox checked={approved} disabled={!text.trim()} onCheckedChange={v=>setApproved(v===true)}/>I’ve checked this text. It reflects my experience.</label><button className="secondary full" disabled={!approved||!text.trim()} onClick={copy}><Copy/>Copy review</button><button className="quiet" onClick={()=>{update('');setOriginal('');setSelected([]);setApproved(false);setReported([]);setAudio(null);toast('Draft cleared on this device.');}}>Clear my draft</button></section>
 {job.photos.length>0&&<section className="panel"><h2><span className="step-number">2</span>Choose photos, if you’d like</h2><p>Select the photos you want to save and attach yourself.</p><div className="photo-grid">{job.photos.map(p=><div key={p.id} className="photo-card"><SecurePhoto src={photoURL(p.id)} alt={p.label}/><label className="photo-caption"><Checkbox checked={selected.includes(p.id)} aria-label={`Select ${p.label}`} onCheckedChange={v=>setSelected(v===true?[...selected,p.id]:selected.filter(id=>id!==p.id))}/>{p.label}</label></div>)}</div><button className="secondary full" style={{marginTop:'1rem'}} disabled={!selected.length} onClick={savePhotos}><Download/>Save selected photos ({selected.length})</button><small style={{marginTop:'.6rem'}}>On a phone, choose Save Images or Save to Files if offered. If downloads are blocked, open an individual photo below.</small><div className="actions">{selected.map(id=><a key={id} href={photoURL(id,true)} target="_blank" rel="noopener noreferrer">Open {job.photos.find(p=>p.id===id)?.label}</a>)}</div></section>}
 <section className="panel" id="destinations"><h2><span className="step-number">{job.photos.length?3:2}</span>Choose where to share</h2><p>You’ll choose your rating and submit on the next page. Your draft stays here.</p>{!destinations.length&&<div className="notice">Review links haven’t been added to this sample yet. You can still try writing, selecting photos, and copying your text.</div>}{destinations.map((p,i)=><div className="destination" key={p}><div className="destination-heading"><h3>{platformNames[p]}</h3>{i===0&&<span className="badge">Start here</span>}</div><small>{p==='apple'?'Apple Maps offers ratings and photos where available.': 'Paste your text, choose your rating, and attach any saved photos.'}</small><a className="button full" href={job.links[p]} target="_blank" rel="noopener noreferrer" onClick={()=>track('click',p)}>Continue to {platformNames[p]}</a><label className="selection-label"><Checkbox checked={reported.includes(p)} onCheckedChange={v=>{if(v===true){track('reported',p);setReported([...reported,p]);}else setReported(reported.filter(x=>x!==p));}}/>I submitted on {platformNames[p]}</label><small>This is your confirmation; the portal cannot verify publication.</small></div>)}</section>
 <footer className="footer"><p>Thank you for sharing your experience.</p>{job.links.yelp&&<a href={job.links.yelp} target="_blank" rel="noopener noreferrer" onClick={()=>track('click','yelp')}>Business information on Yelp</a>}<p>Your draft is stored on this device. Audio is sent for transcription only when voice transcription is connected.</p></footer><Toaster richColors/></main>;
}
